language: android
sudo: required
jdk: oraclejdk8

before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/

env:
 global:
 - ANDROID_API=26
 - EMULATOR_API=22
 - ANDROID_BUILD_TOOLS=26.0.1
 - ADB_INSTALL_TIMEOUT=5 # minutes

android:
 components:
 - tools
 - platform-tools
 - build-tools-$ANDROID_BUILD_TOOLS
 - android-$ANDROID_API
 - android-22
 - extra-google-m2repository
 - extra-android-m2repository # for design library
 - addon-google_apis-google-19 # google play services
 - sys-img-armeabi-v7a-addon-google_apis-google-22
 licenses:
 - android-sdk-preview-license-.+
 - android-sdk-license-.+
 - google-gdk-license-.+

addons:
  apt_packages:
    - pandoc
  artifacts:
    paths:
    - $(git ls-files -o | grep build/outputs | tr "\n" ":")

before_install:
- pip install --user codecov
- chmod +x gradlew
- ./gradlew dependencies || true

after_failure:
- pandoc builder/build/reports/tests/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'

after_success:
- ./gradlew jacocoFullReport
- codecov

script:
- ./gradlew check -PdisablePreDex --continue --stacktrace
- android-wait-for-emulator
- adb devices
- adb shell input keyevent 82 &
- ./gradlew connectedAndroidTest -PdisablePreDex --continue --stacktrace
- rm /home/travis/.gradle/caches/2.8/plugin-resolution/cache.properties.lock

after_script:
- for f in app/build/outputs/lint-results.html; do pandoc $f -t plain; done
- for f in data/build/outputs/lint-results.html; do pandoc $f -t plain; done

# Tutorial here: https://medium.com/@harmittaa/travis-ci-android-example-357f6e632fc4

